### ISSUE TITLE
feature request: comply with media extension of desktops

### ISSUE THREAD

**Issue by ekm507** [aabiji/muse#4]
it would be great if you can manage muse (play and pause it) from media player extensions of desktops. it will also cause muse to be controllable with play/pause keyboard keys.

thank you!

**Comment by aabiji** [comment]
I don't think I understand your request. What do you mean by "media player extensions of desktops"? Also, when you say "play/pause keyboard keys" do you mean like a literal keyboard key or a keyboard shortcut? Sorry.

**Comment by ekm507** [comment]
first of all, thank you again for your contributions to free software. also thank you for your fast response in other issues.

all Desktops like Gnome, KDE, etc have media player controller extensions/widgets that work with a protocol called mpris.
![image](https://github.com/aabiji/muse/assets/13185969/8a4fb89b-4819-4ae1-93d8-baab6c6581bd)
![image](https://github.com/aabiji/muse/assets/13185969/6eb782af-567a-44b7-85aa-93cc15361135)

apps can be compatible with this, so it can control them by sending commands like play, pause, next and seek. I believe they talk via D-Bus protocol.
this is some documentation for D-Bus protocol:
https://develop.kde.org/docs/features/d-bus/introduction_to_dbus/
here's official page of mpris protocol:
https://specifications.freedesktop.org/mpris-spec/latest/

yes, I mean literal keyboard keys. some keyboards (most of laptop keyboards) have these keys. for them to work, you do not need to do anything other than adding mpris compatibility.
![image](https://github.com/aabiji/muse/assets/13185969/4888415a-ea05-4d73-932f-6ff549e85494)

**Comment by aabiji** [comment]
Ok, that seems interesting ... I'll see what I can do. Thanks for the clarifications.

**Comment by aabiji** [comment]
Hey! Mpris offers a lot of functionality while muse (purposefully) doesn't. I'm thinking we could just replicate the cli functionality: play and pause playback. However, that would mean that most of the functionality offered by mpris would be disabled. Would that be ok?

**Comment by ekm507** [comment]
I believe that muse does not need all the functionality of Mpris because it is a background music player app and not something like VLC.
so  I believe that just play and pause functionalities are enough. at least for now.

**Comment by aabiji** [comment]
Alright.

**Comment by aabiji** [comment]
Hey! I'm sorry and I know this sounds cowardly, but could we drop this feature? I've run into a huge roadblock implementing the feature (would need to refactor the server to make it async) and I'm losing the motivation to work on the feature.

**Comment by aabiji** [comment]
Hey! I'm sorry and I know this sounds cowardly, but could we drop this feature? I've run into a huge roadblock implementing the feature (would need to refactor the server to make it async) and I'm losing the motivation to work on the feature. 
If you would like to contribute the feature I would be glad. I made some progress in the mpris-support branch. However if you would not like to, I can just delete the branch and close this issue.
Sorry.

**Comment by ekm507** [comment]
Hi!
Of course! It's your own personal project after all.
I enjoy using muse and thanks for your great contributions to free software.
Do not delete the branch. Keep it for future.
