### ISSUE TITLE
panic in muse play

### ISSUE THREAD

**Issue by ekm507** [aabiji/muse#5]
I had paused muse for 1 hour. then I executed `muse play` command. it gave me an Error:

```
» muse play

thread 'main' panicked at src/net.rs:47:44:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

then config file `~/.muse.conf` got reset so it had no directories in it. so when I retried `muse play` it didn't play.

## my system

Gnu/Linux Debian 12  running latest commit of muse from main branch.

thanks

**Comment by aabiji** [comment]
I'm sorry if this sounds unrealistic, but could you generate a backtrace (run `RUST_BACKTRACE=1 muse play`)? Strangely, I wasn't able to replicate the bug.

**Comment by ekm507** [comment]
I was not able to reproduce it either! I will try to find out when it happens and but till then, you can close this issue.

all I could find is that when you run `muse pause` when server is not running, config file gets reset. maybe you could solve this one?
